#!/usr/bin/env php
<?php
namespace Call;

include_once "Conf/conf.class.php";
include_once "Enum/Enum.php";

use Call\Conf\Config;
use Call\Enum\Enum;
use Call\Object\DeliveryOrder;
use Call\Object\EntryOrder;

(new Config())->loadConf('Web/AppMethod.php');
# 获取 method 值
$method = php_sapi_name() == 'cli' ? $argv[1] : $_GET['method'];

include_once DIR_PATH."/Object/EntryOrder.php";
include_once DIR_PATH."/Object/DeliveryOrder.php";

switch ($method) {
    case Enum::$delivery:
        $res = (new DeliveryOrder())->confirm($method);
        break;

    case Enum::$inStock:
        $res = (new EntryOrder())->confirm($method);
        break;

    case Enum::$outStock:
        $res = ['outStock'];
        break;

    case Enum::$refund:
        $res = ['refund'];
        break;

    default:
        throw new \Exception("Invalid Status");
}

print_r($res);
